FROM node:20
WORKDIR /app
COPY serbia-worker/package*.json ./serbia-worker/
RUN cd serbia-worker && npm install
COPY serbia-worker ./serbia-worker
WORKDIR /app/serbia-worker
EXPOSE 8787
CMD ["node", "server.js"]
